### ISSUE TITLE
When pulling images CI fails

### ISSUE THREAD

**Issue by nabim777** [owncloud/files_external_ftp#110]
https://drone.owncloud.com/owncloud/files_external_ftp/2123/5/3

When pulling the latest docker images https://hub.docker.com/r/hauptmedia/proftpd.
 The CI is been failing since 5 days.

Need investigation

![image](https://github.com/owncloud/files_external_ftp/assets/61624650/32fe0c8b-0e06-43eb-a87a-13abfbd52677)

**Comment by SagarGi** [comment]
The upstream image needs may be need an update. when pulling locally it gives: 

```console
 docker pull hauptmedia/proftpd:latest
latest: Pulling from hauptmedia/proftpd
[DEPRECATION NOTICE] Docker Image Format v1 and Docker Image manifest version 2, schema 1 support is disabled by default and will be removed in an upcoming release. Suggest the author of docker.io/hauptmedia/proftpd:latest to upgrade the image to the OCI Format or Docker Image manifest v2, schema 2. More information at https://docs.docker.com/go/deprecated-image-specs/

```
The docker image format needs to be upgraded by the author

**Comment by phil-davis** [comment]
I raised issue https://github.com/hauptmedia/docker-proftpd/issues/1

If they respond and update the image, then good. Otherwise we can make our own. Let's wait until after the Easter break...

**Comment by DeepDiver1975** [comment]
https://github.com/driesva/docker-proftpd

Maybe this fork is an option

**Comment by SagarGi** [comment]
> I raised issue [hauptmedia/docker-proftpd#1](https://github.com/hauptmedia/docker-proftpd/issues/1)
> 
> If they respond and update the image, then good. Otherwise we can make our own. Let's wait until after the Easter break...

@DeepDiver1975 @phil-davis sure that can be done.
