### ISSUE TITLE
Fails code integrity check

### ISSUE THREAD

**Issue by ekgermann** [owncloud/files_external_ftp#16]
git clone seems to be missing the file integrity check info.

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- files_external_ftp
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.

Raw output
==========
Array
(
    [files_external_ftp] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

)

**Comment by PVince81** [comment]
It doesn't because we cannot sign every possible git commit with the OC signature.

Please use a released version instead.
