### ISSUE TITLE
[For 10.1] FTP external storage 0.2.1

### ISSUE THREAD

**Issue by pmaier1** [owncloud/files_external_ftp#21]
### Reason
- No feature changes
- [x] Just changed category to "storage" https://github.com/owncloud/files_external_ftp/pull/18
- [x] Maybe wait for PHP 7.2 compatibility https://github.com/owncloud/files_external_ftp/pull/20
- New info.xml
- [x] Set max version to 10 for Semver https://github.com/owncloud/files_external_ftp/pull/29
- ~~root issue: https://github.com/owncloud/files_external_ftp/issues/17~~

### QA
- [ ] Create release branch
- [ ] Create "$version Testplan"
- [x] Test: Install from the provided tarball and enable in ownCloud stable10 @davitol 

**BLOCKER**: https://github.com/owncloud/files_external_ftp/issues/17

### Marketing
- [ ] Check/adapt info.xml stuff https://github.com/owncloud/files_external_ftp/issues/23
- [ ] Check/adapt screenshot https://github.com/owncloud/files_external_ftp/issues/23
- [x] Blog post or other communication if applicable => not needed

### Documentation
- [x] Changes in the docs needed? => not needed

### Build & Marketplace release

All actions to be done on the release branch from here:
- [x] Bump version in info.xml: https://github.com/owncloud/files_external_ftp/pull/30
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version - $currentDate' (ex: 3.1.5 - 2018-08-01): https://github.com/owncloud/files_external_ftp/pull/30
- [x] Create github tag for 'v${version}RC1'
- [x] Build and sign RC tarball from github tag 'v${version}RC1' with `make dist` => https://cloud.owncloud.com/index.php/s/JIEIqKJaF4XNNPJ
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing
- [x] Create github tag for final 'v${version}'
- [x] Build and sign final tarball from github tag 'v${version}' with `make dist`
- [x] Smoke test tarball (at least install + enable)
- [x] Upload to marketplace
- [x] Publish for customers
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Rename QA milestone to '$version'
- [x] Add a new 'Unreleased' section in CHANGELOG.md
- [x] Create PR to merge changes back to the `master` branch: https://github.com/owncloud/files_external_ftp/pull/31

**Comment by patrickjahns** [comment]
Builds are failing - once you have the info.xml/screenshot ready - we can fix travis and get it out

**Comment by patrickjahns** [comment]
@cdamken has reported a blocker - confirmed by me : #17

**Comment by PVince81** [comment]
- [ ] root issue: https://github.com/owncloud/files_external_ftp/issues/17
- [ ] set max-version to 10

**Comment by PVince81** [comment]
currently no time to fix the FTP issue. the workaround is using subfolders.

moving on with the release to make the app compatible with 10.1 / Semver.

@davitol please test RC https://cloud.owncloud.com/index.php/s/JIEIqKJaF4XNNPJ

**Comment by davitol** [comment]
@PVince81 Tarball is QA-ready
