### ISSUE TITLE
Standardize CI infrastructure

### ISSUE THREAD

**Issue by phil-davis** [owncloud/files_external_ftp#28]
- [x] move from Travis to drone
- [x] implement owncloud/coding-standard in ``vendor-bin``
- [x] add ``test-php-unit`` to ``Makefile`` and use it from drone
- [x] move unit tests into ``tests/unit`` folder
- [x] review the CI infrastructure and standardize anything else

Part of issue https://github.com/owncloud/QA/issues/582

**Comment by phil-davis** [comment]
Also see #26 - add PHP7.2 to stable10
Include a suitable range of PHP versions and core master+stable10 in the test matrix.

**Comment by phil-davis** [comment]
PRs #36 #37 #38 done - they get CI running and passing in both travis and drone

**Comment by phil-davis** [comment]
Waiting for repo settings to be adjusted:
- require drone
- do not require travis
- add codecov_token

then #39 should pass, and a new PR can be raised to delete `.travis.yml` and adjust the badges in `README.md`

**Comment by PVince81** [comment]
@phil-davis I've set drone/pr and removed travis for this repo.

not sure about the codecov_token, is it the same for all our repos ?

**Comment by phil-davis** [comment]
@PVince81 I have no idea about codecov_token. @DeepDiver1975 has done it in other repos.

**Comment by phil-davis** [comment]
codecov_token done. PR #40 merged. All actions complete.
